### ISSUE TITLE
Please add an entry for avoiding mutable global variables

### ISSUE THREAD

**Issue by kummahiih** [rednafi/py-sanity#5]
Please add an entry for avoiding mutable global variables, because it makes code less modular, harder to test, debug and understand. The reasons are:

- They hide the dependencies between the functions and classes and it is really hard to see how different parts of code are related to each other. This makes the usage, refactoring and testing hard, because you have no idea in what state the global variables should be in order to run the code successfully. This means you have to understand the whole code base in order to modify a single point of global variable usage. If your code base is changing actively, you are new in the project or is so big that it is hard to remember it completely this means you have to bublesort through all N previous functions and classes that use the global variable in order to write the function 'N+1'. This makes the usage of the global variables literally exponentially worse way to program compared to the usage of technique called dependency injection in large software projects. 

- If you run tests in parallel the tests mess up the global state.

- If you debug a deep chain of functions, it is not easy to pick all the variables you have to monitor.

- They tend to waste developer time in the form of merge conflicts.

- They tend to put more workload to the persons responsible for the variables or manager classes and functions which manipulate these variables because of their central role and might cause mental breakdown if the work load is too high

**Comment by rednafi** [comment]
Hi, thanks for your input. Looks legit. Could you please make a new section named `global variables` under the `code guidelines` section and send a PR?
Here's where you can add that via markdown.

https://github.com/rednafi/pysanity/blob/master/docs/README.md

**Comment by kummahiih** [comment]
Ok. It'll take a week or smth. Feeling lazy

**Comment by rednafi** [comment]
Ha ha... don't worry. I'll do it then. Thanks.

**Comment by rednafi** [comment]
Added that ...:)
