### ISSUE TITLE
Broken link on the repo's "About" section.

### ISSUE THREAD

**Issue by luigibertaco** [rednafi/py-sanity#6]
Hey guys, just letting you know that the short link showing on the repo's "About" section is broken.

It redirects you to [https://github.com/rednafi/pysanity/blob/master/docs/guidelines.md](https://github.com/rednafi/pysanity/blob/master/docs/guidelines.md) instead of sending to [https://pysanity.netlify.com/](https://pysanity.netlify.com/) (what I was expecting it to be, but could be wrong).

![image](https://user-images.githubusercontent.com/1386513/89147496-27f0e500-d59a-11ea-969f-7f7c032cf003.png)

**Comment by rednafi** [comment]
Hi thanks for mentioning it. You are right. Updating the link.

**Comment by rednafi** [comment]
Fixed.
